on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # https://github.com/actions/runner-images
  debug-job:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15, macos-13, windows-2025, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: mxschmitt/action-tmate@v3
