on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos-aarch64:
    runs-on: macos-15
    steps:
      - uses: mxschmitt/action-tmate@v3
