on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # https://github.com/actions/runner-images
  debug-job:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15, macos-13, windows-2025, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: mxschmitt/action-tmate@v3

  # https://github.com/mxschmitt/action-tmate/issues/216
  debug-windows-11-arm:
    runs-on: windows-11-arm
    steps:
    - uses: msys2/setup-msys2@v2
    - uses: mxschmitt/action-tmate@v3
      with:
        msys2-location: ${{ steps.setup-msys2.outputs.msys2-location }}

  debug-freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: vmactions/freebsd-vm@v1
        with:
          copyback: false
          release: "14.2"
      - shell: freebsd {0}
        run: set -ex && pkg update && pkg install -y git
      - run: echo "connect with 'ssh freebsd'"
      - uses: mxschmitt/action-tmate@v3
